### ISSUE TITLE
Fix Django Template Syntax Error in all HTML pages

### ISSUE THREAD

**Issue by sneha-nitdgp** [opencodeiiita/Shopping-Cart#1]
This is a good first issue for beginners. TemplateSyntaxError error appears while opening any page (such as http://127.0.0.1:8000/shop/).

 Just a one-line change can fix this. Go ahead, and contribute!
![Capture](https://user-images.githubusercontent.com/68119292/136251309-f459953f-4689-471e-a032-14920e5347ba.PNG)

## Rules
We follow **FCFS**, **F**irst **C**ome **F**irst **S**erve

The **first three** users **to claim** this Issue gets the chance to work on it
They will each get **2 days** to solve the Issue

If a user doesn't respond or solve the Issue
the mentor may **unassign** them from the Issue and allow another user to work on it.

At the end, we will select the **best of three**
So keep your modifications clean and meaningful.

**To claim**, simply comment with any of the following terms
- I would like to work on this feature
- May I claim this Issue?
- Claim

**Comment by batflarrow** [comment]
Claim

**Comment by sneha-nitdgp** [comment]
@batflarrow Assigned!

**Comment by karankc23** [comment]
claim

**Comment by jalanprakhar** [comment]
c

**Comment by ghost** [comment]
claim

**Comment by batflarrow** [comment]
Hey, @sneha-nitdgp I fixed the Template Syntax Error by replacing staticfiles with static in all HTML pages, Do I have to do anything else as well..?

**Comment by sneha-nitdgp** [comment]
@batflarrow Yes that's it. Did you check by opening all pages in localhost? If yes, then you can create a pull request.

**Comment by batflarrow** [comment]
> @batflarrow Yes that's it. Did you check by opening all pages in localhost? If yes, then you can create a pull request.

Yes, but it was showing some other error Which was an Operational error no such table:django_session and other table names in other pages is this what should have happened..? 

![image](https://user-images.githubusercontent.com/56157504/136430078-c66f65af-66aa-4cf4-b336-88044c111466.png)
Is this supposed to have happened or there is an issue from my end while setting up the project..? I am a bit new to Django.😅

**Comment by sneha-nitdgp** [comment]
@batflarrow Run this command python manage.py migrate --run-syncdb

**Comment by batflarrow** [comment]
> migrate --run-syncdb

Ohk thanks lemme try it..

**Comment by batflarrow** [comment]
> python manage.py migrate --run-syncdb

Okay now they are working

**Comment by batflarrow** [comment]
Yup, nobody belives me :(

**Comment by batflarrow** [comment]
Thanks @garvitchittora
